/* Copyright (c) 2018 Qualcomm Technologies International, Ltd. */
/*    */
/**
 * \file
 * Implementations of non-autogenerated tws_shadow-related trap calls
 */


#include "trap_api/trap_api_private.h"

#if TRAPSET_ACL_CONTROL

bool AclReceiveEnable(const tp_bdaddr *addr, bool enable, uint32 timeout)
{
    IPC_ACL_RECEIVE_ENABLE ipc_send_prim;
    IPC_BOOL_RSP ipc_recv_prim;
    ipc_send_prim.addr = (const TP_BD_ADDR_T *)addr;
    ipc_send_prim.enable = enable;
    ipc_send_prim.timeout = timeout;
    ipc_send(IPC_SIGNAL_ID_ACL_RECEIVE_ENABLE, &ipc_send_prim, sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_ACL_RECEIVE_ENABLE_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

acl_rx_processed_status AclReceivedDataProcessed(const tp_bdaddr *addr, uint32 timeout)
{
    IPC_ACL_RECEIVED_DATA_PROCESSED ipc_send_prim;
    IPC_ACL_RX_PROCESSED_STATUS_RSP ipc_recv_prim;
    ipc_send_prim.addr = (const TP_BD_ADDR_T *)addr;
    ipc_send_prim.timeout = timeout;
    ipc_send(IPC_SIGNAL_ID_ACL_RECEIVED_DATA_PROCESSED, &ipc_send_prim, sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_ACL_RECEIVED_DATA_PROCESSED_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

bool AclTransmitDataPending(const tp_bdaddr *addr)
{
    IPC_ACL_TRANSMIT_DATA_PENDING ipc_send_prim;
    IPC_BOOL_RSP ipc_recv_prim;
    ipc_send_prim.addr = (const TP_BD_ADDR_T *)addr;
    ipc_send(IPC_SIGNAL_ID_ACL_TRANSMIT_DATA_PENDING, &ipc_send_prim, sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_ACL_TRANSMIT_DATA_PENDING_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

#endif /* TRAPSET_ACL_CONTROL */

#if TRAPSET_SHADOWING

uint16 AclHandoverPrepare(const tp_bdaddr *acl_addr, const tp_bdaddr *recipient)
{
    IPC_ACL_HANDOVER_PREPARE ipc_send_prim;
    IPC_UINT16_RSP ipc_recv_prim;
    ipc_send_prim.acl_addr = (const TP_BD_ADDR_T *)acl_addr;
    ipc_send_prim.recipient = (const TP_BD_ADDR_T *)recipient;
    ipc_send(IPC_SIGNAL_ID_ACL_HANDOVER_PREPARE, &ipc_send_prim, sizeof(ipc_send_prim));
    (void)ipc_recv(IPC_SIGNAL_ID_ACL_HANDOVER_PREPARE_RSP, &ipc_recv_prim);
    return ipc_recv_prim.ret;
}

#endif /* TRAPSET_SHADOWING */

