/**************************************************************************/
/* Copyright (c) 2019 Qualcomm Technologies International, Ltd.           */
/* Autogenerated File, Do Not Edit                                        */
/*                                                                        */
/* This file exports public entry points from patch code                  */
/*                                                                        */
/**************************************************************************/
#ifndef SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H
#define SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H

#define PATCH_BUILD_ID                           8988

#define PATCH_ENTRY_CREATE_MUTE_OP               0x04003bd3 /* $_create_mute_op */
#define PATCH_ENTRY_CBOPS_MUTE_ENABLE            0x04003c0d /* $_cbops_mute_enable */
#define PATCH_ENTRY_CBOPS_MUTE_RESET             0x04003c13 /* $_cbops_mute_reset */
#define PATCH_ENTRY_TTP_UPDATE_TTP_FROM_SOURCE_TIME 0x04003c2f /* $_ttp_update_ttp_from_source_time */
#define PATCH_ENTRY_GET_BT_ADDRESS               0x04003ead /* $_get_bt_address */
#define PATCH_ENTRY_SET_LIC_DEBUG                0x04003fcd /* $_set_lic_debug */
#define PATCH_ENTRY_AUDIO_PIOS_SET_DIRECTION     0x04004c47 /* $_audio_pios_set_direction */
#define PATCH_ENTRY_AUDIO_PIOS_SET_OUTPUTS       0x04004cd5 /* $_audio_pios_set_outputs */
#define PATCH_ENTRY_AUDIO_PIOS_GET_INPUTS        0x04004d11 /* $_audio_pios_get_inputs */
#define PATCH_ENTRY_AUDIO_THREAD_RPC_CALL        0x040050e3 /* $_audio_thread_rpc_call */
#define PATCH_ENTRY_AUDIO_THREAD_RPC_IS_ACTIVE   0x040051ad /* $_audio_thread_rpc_is_active */
#define PATCH_ENTRY_AUDIO_THREAD_GET_RPC_ACTIVE  0x040051c7 /* $_audio_thread_get_rpc_active */
#define PATCH_ENTRY_AUDIO_THREAD_OFFLOAD_IS_ACTIVE 0x040051db /* $_audio_thread_offload_is_active */
#define PATCH_ENTRY_AUDIO_THREAD_OFFLOAD_IS_ENABLED 0x040051f7 /* $_audio_thread_offload_is_enabled */
#define PATCH_ENTRY_AUDIO_THREAD_COPY_FFT_TWIDDLE 0x04005145 /* $_audio_thread_copy_fft_twiddle */
#define PATCH_ENTRY_AUDIO_THREAD_SET_UP_APTX     0x04005181 /* $_audio_thread_set_up_aptx_offload */
#define PATCH_ENTRY_SETUP_CBOPS_DC_OFFSET_COMPENSATION 0x04006927 /* $_setup_cbops_dc_offset_compensation */

#endif /* SUBSYS3_PATCH0_FW000012B2_MAP_PUBLIC_H */
